[pytest]
markers =
    smoke: vital core functional tests
    storage: tests related to Robin.io storage layer
    networking: tests for 5G and container networking
    regression: full suite for final release validation
    reg: regression